FROM    alpine:3.17

RUN     apk update && apk upgrade \
        && apk add --update dumb-init mariadb mariadb-common mariadb-client mariadb-server-utils

EXPOSE  3306

COPY    ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/
COPY    ./tools /var/www/

RUN     service mysql start && mysql < /var/www/initial_db.sql && rm -f /var/www/initial_db.sql;

CMD ["mysqld"]
