version: "3.5"

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: /home/andrepaul/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/andrepaul/data/mariadb

networks:
  inception:
    name: inception
    driver: bridge

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
    - .env
    volumes:
    - db:/var/lib/mysql
    networks:
    - inception
    restart: always

  nginx: 
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wp
    build: ./requirements/wordpress
    volumes:
     - wp:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
