FROM    alpine:3.17

RUN     apk update && apk upgrade \
        && apk add --update dumb-init mariadb mariadb-common mariadb-client mariadb-server-utils

COPY    ./conf/mariadb.conf /etc/mysql/mariadb.conf
COPY    ./tools /var/www/

RUN     service mysql start && mysql < /var/www/db_set.sql && rm -f /var/www/db_set.sql;

EXPOSE  3306

CMD ["mysqld"]
